### ISSUE TITLE
Gruvbox Light Cursor's Foreground Color is equal with Cursor's Background

### ISSUE THREAD

**Issue by levirs565** [mbadolato/iTerm2-Color-Schemes#273]
Gruvbox Light Cusor Foreground Color is equal with Background Color. This make cursor is black and text is hidden.

https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/xrdb/Gruvbox%20Light.xrdb

```c
#define Cursor_Color #282828
#define Cursor_Guide_Color #3c3836
#define Cursor_Text_Color #282828
```

https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/wezterm/Gruvbox%20Light.toml

```toml
cursor_bg = "#282828"
cursor_border = "#282828"
cursor_fg = "#282828"
brights = ["#9d8374","#cc241d","#98971a","#d79921","#458588","#b16186","#689d69","#7c6f64"]
```

Cursor Foreground Color musr invert of Backgroun Color. I use `#fbf1c7` for Cursor's Foreground.
